"""Added index for parent_id foreign key column

Revision ID: c65208f75e04
Revises: 3fda7dd49637
Create Date: 2025-01-04 07:08:09.419036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c65208f75e04'
down_revision: Union[str, None] = '3fda7dd49637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    # ### end Alembic commands ###
